[tool.poetry]
name = "aws_wrapper"
version = "0.1.0"
description = "Amazon Web Services (AWS) Advanced Python Wrapper"
authors = ["Amazon Web Services"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8.1"
psycopg = "^3.1.9"
psycopg-binary = "^3.1.9"
pytest = "^7.3.1"
pytest-mock = "^3.10.0"
mypy = "^1.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pep8-naming = "^0.13.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
